# Book settings
title: InsiderTrader
author: Anshitha
logo: docs/images/logo.jpg


html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
 
only_build_toc_files: true
